[package]
name = "http-utils"
version = "0.1.0"
authors = ["Pablo Deymonnaz <deymonnaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version="2.0", features=["rust-tls"] }
actix-rt = "1.1.1"
actix-service = "1.0.5"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"
reqwest = { version = "0.10.4", default-features = false, features = ["blocking", "json"] }