[package]
name = "http-utils"
version = "0.1.0"
authors = ["Pablo Deymonnaz <deymonnaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version="2.0", features=["rust-tls"] }
actix-multipart = "0.2.0"
actix-rt = "1.1.1"
actix-service = "1.0.6"
futures = "0.3.5"
async-std = "1.6.4"
sanitize-filename = "0.2"
anyhow = "1.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"
uuid = { version = "0.8.1", features = ["v4"] }

reqwest = { version = "0.10.4", default-features = false, features = ["blocking", "json"] }